### ISSUE TITLE
Need to use test waiter for css3 transition complete or exclude transitions during acceptance tests

### ISSUE THREAD

**Issue by cristinawithout** [peec/ember-css-transitions#16]
Can't test whether an element has been successfully shown and hidden in an acceptance if you add a transition to show/hide it using this addon. This is because the tests don't wait for CSS3 transitions to complete.

Either need to register a [test waiter](http://emberjs.com/api/classes/Ember.Test.html#method_registerWaiter) that completes on the transition complete events or exclude the transitions during test when `Ember.testing` is true.

**Comment by cristinawithout** [comment]
Actually, I see that the release for v0.1.4 says it should fix acceptance tests in the release notes. That release doesn't seem to be published to npm though. The latest that installs through npm is 0.1.2. Trying to install 0.1.4 or 0.1.3 gives me version not found.

**Comment by cristinawithout** [comment]
Installed from latest commit. (git://github.com/peec/ember-css-transitions.git#f7f7ac60e40723a55aaecbd4e5c7d2c383a02cbc)

Still has same issue.

**Comment by miguelcobain** [comment]
@cristinawithout I released 0.1.5.

It should be more test friendly using ember's `wait()` helper.
It would be great if you could test it and let me know.

**Comment by miguelcobain** [comment]
Please reopen if problem persists.
