### ISSUE TITLE
customisable computeTimeout

### ISSUE THREAD

**Issue by kernel-io** [peec/ember-css-transitions#18]
Hi guys; love the library, however, I was wondering if you would be open to a PR that enables us to roll our own computeTimeout Logic, I know I can override the function, but its marked as private so I would prefer a sanctioned path.

The reason I'm asking is because there are times when I am actually animating child elements, but the parent element gets destroyed before the child elements are finished with their animations.

So far I have been getting around it by defining a transition on some bogus property at the parent element level. It would be cool to be able to write your own logic that computes timeout based on child elements etc.

**Comment by miguelcobain** [comment]
Idea: use timeout properties to instead of `computeTimeout` if they're available.
The `transition` function should accept a timeout value. If it is undefined, we fallback to compute timeout.

Timeouts:
- `enterTimeout` would be used for animating the component insertion
- `leaveTimeout`  would be used for animating the component destroy
- for animating class add/removal, we could extend the scheme we're using, e.g `transitionClassNameBindings: ['isOpen::300', 'pinned:is-pinned:450']`

We would essentially do this to extract the timeout in the `_setupTriggerObservers` function:
```js
let [propName, className, timeout] = classExp.split(':');
```

This approach is basically how react does.
Would this solve your problem and would you be willing to PR such a functionality?

**Comment by kernel-io** [comment]
Nice ideas! Looks pretty similar to react, I like the transitionClassNameBindings syntax also.

I would be willing to PR a proposal, possibly in the coming week(s), getting close to launching the product I'm working on at the moment so all effort is focused on that. Doesn't seem like it would be too difficult to implement.

**Comment by miguelcobain** [comment]
One last detail, `enterTimeout` and `leaveTimeout` could default to the same value as a third property, since they have very frequently the same value:

```js
enterTimeout: computed.reads('transitionTimeout'),
leaveTimeout: computed.reads('transitionTimeout'),
```

This way the user could override them or use the general property. The rest of the Mixin code would be agnostic of this defaulting behaviour and would just use the properties directly.

**Comment by kernel-io** [comment]
still alive, but still swamped with work 😔

**Comment by eduscrakozabrus** [comment]
i have this is issue

in Tailwind 2.0

{{#if this.account.openMobileMenu}}
  <div class='lg:hidden'>
    <div
      class="fixed inset-0 flex z-40 {{
        if (not this.account.openMobileMenu) 'hidden' ''
      }}"
    >
      <div
        class='fixed inset-0'
        {{css-transition
          enterClass='opacity-0'
          enterActiveClass='transition-opacity ease-linear duration-300'
          enterToClass='opacity-100'
          leaveClass='opacity-100'
          leaveActiveClass='  duration-300'
          leaveToClass='opacity-0'
        }}
      >
..................
animation work only enter, but leave dont work . Parent div deleted toggle by this.account.openMobileMenu

**Comment by eduscrakozabrus** [comment]
`{{#if this.account.openMobileMenu}}
  <div class='lg:hidden'>
    <div
      class="fixed inset-0 flex z-40 {{
        if (not this.account.openMobileMenu) 'hidden' ''
      }}"
    >
      <div
        class='fixed inset-0'
        {{css-transition
          enterClass='opacity-0'
          enterActiveClass='transition-opacity ease-linear duration-300'
          enterToClass='opacity-100'
          leaveClass='opacity-100'
          leaveActiveClass='  duration-300'
          leaveToClass='opacity-0'
        }}
      >`

**Comment by eduscrakozabrus** [comment]
<div
        class='fixed inset-0'
        {{css-transition
          enterClass='opacity-0'
          enterActiveClass='transition-opacity ease-linear duration-300'
          enterToClass='opacity-100'
          leaveClass='opacity-100'
          leaveActiveClass='  duration-300'
          leaveToClass='opacity-0'
        }}
      >

**Comment by pdud** [comment]
Hey @eduscrakozabrus

If you are able to provide more complete code example (full templates of child and parent). I can try provide a better answer than the following.

Perhaps this might be of use to you.

https://github.com/peec/ember-css-transitions/issues/48

Or perhaps, do you need the `transition-opacity` class on the `leaveActiveClass` arg?

**Comment by eduscrakozabrus** [comment]
This is work solution!

`{{#if this.account.openMobileMenu}}
  <div 
  
  {{did-insert this.showChild this.account.openMobileMenu}}
  {{did-update this.showChild this.account.openMobileMenu}}
   class='lg:hidden'>
    <div
      class="fixed inset-0 flex z-40 {{
        if (not this.account.openMobileMenu) 'hidden' ''
      }}"
    >
      {{#if this.isShowChild}}
      <div
        class='fixed inset-0'
        {{css-transition
          enterClass='opacity-0'
          enterActiveClass='transition-opacity ease-linear duration-300'
          enterToClass='opacity-100'
          leaveClass='opacity-100'
          leaveActiveClass='  duration-300'
          leaveToClass='opacity-0'
        }}
      >
      
        <div class='absolute inset-0 bg-gray-600 opacity-75'></div>
      </div>
      {{/if}}

      {{#if this.isShowChild}}
      <div
        class='relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-white dark:bg-gray-700'
        {{css-transition
        
          enterClass='-translate-x-full'
          enterActiveClass='transition ease-in-out duration-300 transform'
          enterToClass='translate-x-0'
          leaveClass='translate-x-0'
          leaveActiveClass=' duration-300 transform'
          leaveToClass='-translate-x-full'
        }}
      >
        <div class='absolute top-0 right-0 -mr-14 p-1'>
          <button
            onclick={{action 'hideChild'}}
            class='flex items-center justify-center h-12 w-12 rounded-full focus:outline-none focus:bg-gray-600'
            aria-label='Close sidebar'
          >
            <svg
              class='h-6 w-6 text-white'
              stroke='currentColor'
              fill='none'
              viewBox='0 0 24 24'
            >
              <path
                stroke-linecap='round'
                stroke-linejoin='round'
                stroke-width='2'
                d='M6 18L18 6M6 6l12 12'
              ></path>
            </svg>
          </button>
        </div>

        <div class='mt-5 flex-1 h-0 overflow-y-auto'>
          
          <nav class='px-3 mt-6'>
            <div class='space-y-1'>
              {{#each (sort-by 'order' this.menuItems) as |menu|}}
                <LinkTo
                  @route={{menu.route}}
                  class={{
                    if
                    (is-equal
                      this.router.currentRouteName (concat menu.route '.index')
                    )
                    'group flex items-center px-2 py-2 text-sm leading-5 font-medium rounded-md text-gray-900 bg-gray-200 focus:outline-none focus:bg-gray-50 transition ease-in-out duration-150 dark:text-gray-300 dark:bg-gray-700  dark:focus:bg-gray-600 '
                    'group flex items-center px-2 py-2 text-sm leading-5 font-medium rounded-md text-gray-800 hover:text-gray-600 hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition ease-in-out duration-150 dark:text-gray-300 dark:bg-gray-700  dark:focus:bg-gray-600 dark:hover:text-gray-300'
                  }}
                  role='menuitem'
                >
                  {{html-safe menu.iconHtml}}
                  {{t menu.translate}}
                </LinkTo>

                {{#if
                  (or
                    (eq
                      this.router.currentRoute.name (concat menu.route '.index')
                    )
                    (eq this.router.currentRoute.parent.name menu.route)
                    (eq this.router.currentRoute.parent.parent.name menu.route)
                  )
                }}
                  <Menu::SubMenu::Desktop @parent={{menu.id}} />
                {{/if}}
              {{/each}}
            </div>

            <Menu::Teams::Desktop />
          </nav>
        </div>
      </div>
      {{/if}}
      <div class='flex-shrink-0 w-14'>
        
      </div>
    </div>
  </div>
{{/if}}`

`import Component from '@glimmer/component';
import { inject as service } from '@ember/service';
import { computed, observer, action } from "@ember/object";
import { tracked } from '@glimmer/tracking';
export default class MenuMainMobileComponent extends Component {
    @service store;
    @service  router
    @service  account;
    @tracked  isShowChild = false

    @action
    showChild() {
        this.isShowChild = true
    }

    @action
    hideChild() {
        this.isShowChild = false
        setTimeout(()=> this.account.openMobileMenu = false,500)
        
    }
    
    @computed("menu.length")
    get menuItems() {
        return this.menu.filter(action => true)
    }

    get menu() {
        return this.store.peekAll('menu')
    }
}
`
