### ISSUE TITLE
Doesn't work with ember-wormhole

### ISSUE THREAD

**Issue by Padchi** [peec/ember-css-transitions#3]
![skarmavbild 2015-11-06 kl 00 22 03](https://cloud.githubusercontent.com/assets/814347/10984831/89ad54e2-841c-11e5-80b8-d4b977eec8b7.png)

**Comment by miguelcobain** [comment]
Can you provide more info on this?
Don't know if this is related with #11. It seems to work fine with ember-wormhole.
I'll close this for now. We can reopen if this still proves to be a problem.
