### ISSUE TITLE
Missing documentation for Ember Octane

### ISSUE THREAD

**Issue by sosickstudio** [peec/ember-css-transitions#30]
The example code provided
````
<div {{css-transition "example"}}>
  <h1>Hello world</h1>
</div>
```` 
doesn't work in Ember Octane, would be awesome to provide an octane example for newbies.

Thanks a lot !

**Comment by miguelcobain** [comment]
Did you add the correct css for that example?
Did you check the documentation site? http://peec.github.io/ember-css-transitions/

**Comment by miguelcobain** [comment]
The addon works just fine on both octane and classic components. We have tests for that. Closing this issue.
