### ISSUE TITLE
Crashes on tear down of elements with {{css-transition}}

### ISSUE THREAD

**Issue by Benjy1979** [peec/ember-css-transitions#32]
If I have an element in a conditional block with Ember-cli 3.16.1 if I apply {{css-transition}}, I get a crash in the ember-css-transition library somewhere.

`css-transition.js:126 Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
    at CssTransitionModifier.addClone (css-transition.js:126)
    at CssTransitionModifier.willRemove (css-transition.js:67)
    at ClassBasedModifierManager.destroyModifier (modifier-manager.js:38)
    at CustomModifierState.destroy (index.js:7052)
    at StringDestroyableDestructor.[DID_DROP] (util.js:355)
    at util.js:304
    at Set.forEach (<anonymous>)
    at SnapshotDestructor.[DID_DROP] (util.js:304)
    at TransactionImpl.commit (runtime.js:1655)
    at EnvironmentImpl.commit (runtime.js:1803)`

It's basically making it unusable, much appreciate a fix

**Comment by miguelcobain** [comment]
By
> an element in a conditional block

you mean something like this?

```hbs
{{#if something}}
  <div {{css-transition "example"}}>
    <h1>Hello world</h1>
  </div>
{{/if}}
```

**Comment by Benjy1979** [comment]
Yes, except in my case it's more octane
` {{#if @isInInsertTextMode}}
         <li {{css-transition "example"}}> 
             <button class="btn toolsmenu__btn" {{on "click" (fn @clickCancelInsertText)}}>Cancel Insert Text</button>
        </li>
    {{/if}}`

**Comment by miguelcobain** [comment]
@Benjy1979 please try with version `1.0.1`. Please reopen if issue still persists.

**Comment by Benjy1979** [comment]
#ROCKSTAR thanks. It works. The same crash seems not to happen now but I accept your invite to reopen if another one blights!
Many thanks!

**Comment by Benjy1979** [comment]
I am from time to time getting this but haven't nailed what causes it exactly yet:

`css-transition.js:135 Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at CssTransitionModifier.addClone (http://localhost:4200/roomviewer-articad2/assets/vendor.js:135932:21)
    at CssTransitionModifier.willRemove (http://localhost:4200/roomviewer-articad2/assets/vendor.js:135871:14)
    at ClassBasedModifierManager.destroyModifier (http://localhost:4200/roomviewer-articad2/assets/vendor.js:138368:16)
    at CustomModifierState.destroy (http://localhost:4200/roomviewer-articad2/assets/vendor.js:25113:16)
    at StringDestroyableDestructor.[DID_DROP] (http://localhost:4200/roomviewer-articad2/assets/vendor.js:69657:18)
    at http://localhost:4200/roomviewer-articad2/assets/vendor.js:69568:23
    at Set.forEach (<anonymous>)
    at didDestroyAssociated (http://localhost:4200/roomviewer-articad2/assets/vendor.js:69567:18)
    at SimpleDestructor.[DID_DROP] (http://localhost:4200/roomviewer-articad2/assets/vendor.js:69681:7)
    at http://localhost:4200/roomviewer-articad2/assets/vendor.js:69606:54`

**Comment by miguelcobain** [comment]
@Benjy1979 Please let me know if you ever find a way to reproduce that consistently.

**Comment by Benjy1979** [comment]
I can see it is consistently happening in my nav bar.

I have something like:

`    {{#if @isInLineDrawingMode}}
        <ul {{css-transition "example"}}>
            <li>
                <button class="btn toolsmenu__btn" {{on "click" @clickCancelLineDrawing}} type="button">
                    Cancel Line Drawing  
                </button>   
            </li>
            <li>
                  <button class="btn toolsmenu__btn" {{on "click" @clickEndLineDrawingMode}} type="button">
                    Finish Line Drawing  
                </button>
            </li>
        </ul>
         <p class="nav-bar-instruction">
            <i class="far fa-question-circle"></i>&nbsp;Click to create points. Join at the red circle.  
        </p>
    {{/if}}

    {{#if @isInDeleteLineDrawingMode}}
        <ul {{css-transition "example"}}>
            <li> 
                <button class="btn toolsmenu__btn" {{on "click"  @clickCancelDeleteLineDrawing}}>Cancel Delete</button>
            </li>
            <li> 
                <button class="btn toolsmenu__btn" {{on "click" (fn @clickDeleteLineDrawing this.unique_id)}}>Delete Line Drawing</button>
            </li> 
        </ul>  
    {{/if}}
 
    {{#if @isInInsertTextMode}}
        <ul {{css-transition "example"}}>
            <li> 
                <button class="btn toolsmenu__btn" {{on "click" @clickCancelInsertText}}>Cancel Insert Text&nbsp;<i class="fas fa-remove-format"></i> </button>
            </li>
        </ul>
    {{/if}}
 
    {{#if showNormalMenuBar}}
        <ul {{css-transition "example"}}>
            <li >
                <button class="btn toolsmenu__btn" {{on "click" @clickAutoScale}} type="button">
                    Fit to Screen <i class="fas fa-expand"></i>
                </button>
            </li>
            
            <li>
                <button class="{{if @panEnabled "enabled"}} btn toolsmenu__btn" {{on "click" @clickLockPanning}} type="button">
                {{#if @panEnabled}}
                    Enable Pan  
                    <i class="fas fa-lock"></i>
                {{else}}
                    Disable Pan 
                    <i class="fas fa-arrows-alt"></i>
                {{/if}} 
                </button>
            </li>

            <li>
                <button class="{{if @lockWallsEnabled "enabled"}} btn toolsmenu__btn" {{on "click" @clickLockWalls}} type="button">    
                {{#if @lockWallsEnabled}}
                    Unlock Walls
                    <i class="fas fa-lock"></i>
                {{else}}
                    Lock Walls
                    <i class="fas fa-arrows-alt"></i>
                {{/if}} 
                </button>
            </li>

        

            <li class="toolsmenu__zoom">
                <button class="btn   insert-text-button" {{on "click" @clickInsertText}} type="button">
                    Insert Text <i class="fas fa-text-height"></i>
                </button>
            </li>

            <li>
                <button class="btn toolsmenu__btn" {{on "click" @clickInsertLines}} type="button">
                    Draw Line <i class="fas fa-long-arrow-alt-up"></i>
                </button>
            </li>

            <li>
                <button class="btn toolsmenu__btn" {{on "click" @onClickUndo}}>
                    Undo <i class="fas fa-undo"></i> 
                </button>
            </li>

            <li>
                <button class="btn toolsmenu__btn" {{on "click" @onClickRedo}}>
                    Redo <i class="fas fa-redo"></i>
                </button>
            </li>
        </ul>

    {{/if}}

`

**Comment by Benjy1979** [comment]
Sorry I'm struggling with the code formatter on here so the top of the code is garbled. But basically speaking it's a conditional template.

**Comment by josemarluedke** [comment]
I was having a similar issue today. I figured that the issue was because I was removing both sibling elements at the same time. However, the modifier relies on the parent as well as the sibling to insert the cloned element. You might be having the same problem here if `@isInDeleteLineDrawingMode` and `@isInInsertTextMode` are becoming `false` at the same time.

A hack solution is to add an element in between that is not removed. For example, an empty `span` tag.

```hbs
{{#if @isInDeleteLineDrawingMode}}
    <ul {{css-transition "example"}}>
        <li> 
            <button class="btn toolsmenu__btn" {{on "click"  @clickCancelDeleteLineDrawing}}>Cancel Delete</button>
        </li>
        <li> 
            <button class="btn toolsmenu__btn" {{on "click" (fn @clickDeleteLineDrawing this.unique_id)}}>Delete Line Drawing</button>
        </li> 
    </ul>  
{{/if}}

<span></span>

{{#if @isInInsertTextMode}}
    <ul {{css-transition "example"}}>
        <li> 
            <button class="btn toolsmenu__btn" {{on "click" @clickCancelInsertText}}>Cancel Insert Text&nbsp;<i class="fas fa-remove-format"></i> </button>
        </li>
    </ul>
{{/if}}
```


Not sure if the modifier could have a fallback if the sibling is also removed.

**Comment by miguelcobain** [comment]
Just FYI, this problem was all due to a change in the behavior of the way destroy hooks work.
Since 3.17 seems like they're called asynchronously with the element disconnected from the DOM.

More information:
- https://github.com/emberjs/ember.js/issues/18795
- https://github.com/emberjs/ember.js/issues/18855#issuecomment-607445112

**Comment by lukemelia** [comment]
I think https://github.com/peec/ember-css-transitions/pull/39 may fix this.

**Comment by Benjy1979** [comment]
Seems to fail the "ember serve" step using Node 12

**Comment by Benjy1979** [comment]
Seems to work well
