### ISSUE TITLE
Support disabling the modifier

### ISSUE THREAD

**Issue by josemarluedke** [peec/ember-css-transitions#33]
First of all, thank you for this addon. 

For building general components, it would be awesome to be able to disable animations per user's request.

For example, we might have a component that has an argument `isAnimationEnabled`, to be able to support this, we need to duplicate all the markup to a version that has the modifier and another that does not have the modifier.

```hbs
{{#if @isAnimationEnabled}}
  <div {{css-transition "example"}}>Something</div>
{{else}}
  <div>Something</div>
{{/if}}
```

With the ability to disable the animation, this could be refactored to:

```hbs
<div {{css-transition "example" isEnabled=@isAnimationEnabled}}>Something</div>
```

Thanks.

**Comment by pdud** [comment]
Another option that could work right now for you is the following?

```hbs
<div {{css-transition (if @isAnimationEnabled "example")}}>Something</div>
```

`ember-css-transition` returns early if a positional argument is not truthy.

--------------------

For @miguelcobain 

How this would implemented for the other PRs:

1. reactjs/react-transition-group v1 appears to use `transitionEnter` and `transitionLeave` as boolean props (link)[https://reactjs.org/docs/animation.html#disabling-animations]

2.  reactjs/react-transition-group v4 (latest) appears to use `enter` and `exit` (and appear) as boolean props (link)[http://reactcommunity.org/react-transition-group/transition#Transition-prop-enter]

3. vue - I can't seem to find a way to do this in Vue.

**Comment by miguelcobain** [comment]
@pdud this actually might help us decide on the react v4 implementation.
Would you be ok with adding that?

Sorry for the delay. I've been swamped with work lately.

**Comment by pdud** [comment]
@miguelcobain I think what I wrote is a bit misleading :(. The Vue way would be to disable like the way I proposed above for ember-css-transitions. A conditional set it to null.

```hbs
<div {{css-transition (if @isAnimationEnabled "example")}}>Something</div>
```

I'd be happy to take any implementation over the finish line with tests and bring it closer in line.

Are you undecided between React V4 and Vue for the next version of this library? I don't have much opinion between the two.

No worries! Thanks for the reply!

**Comment by pdud** [comment]
I guess it's a bit more verbose. Not much in it though.

```
<div {{css-transition
  enterClass=(if @isAnimationEnabled "opacity-0")
  enterActiveClass=(if @isAnimationEnabled "opacity-100")
  ...
>Something</div>

**Comment by miguelcobain** [comment]
@pdud ah, got it. yes, those two seem the best to me.

I guess that nothing stops us from adding those react booleans to the vue-like implementation?

**Comment by pdud** [comment]
@miguelcobain Right, we could certainly do that!
