### ISSUE TITLE
"ember serve" broken with latest updates.

### ISSUE THREAD

**Issue by Benjy1979** [peec/ember-css-transitions#41]
HI,

With node version 12, and 3.19.0 and 3.17 it crashes in the build for ember-css-transitions 1.1.0, but not 1.0.1.
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-css-transitions]) in ember-css-transitions/modifiers/css-transition.js

function(router) {} could not be cloned.

Thanks. APologies I posted this and closed it already but it was because node 10 actually works still, and it threw me off on another machine when it appeared to work until I realised the node version is different.

**Comment by lukemelia** [comment]
I tried to reproduce this locally by using nodenv to switch to node v12.14.0 and run `ember serve` from the `ember-css-transitions` dir and it works as expected. I also opened https://github.com/peec/ember-css-transitions/pull/42 to add a node 12 test run to Travis and that passed as well. Maybe you can give more specific reproduction steps @Benjy1979?

**Comment by Benjy1979** [comment]
Really? I'm confused now because two machines repeated the error, let me see if I get a basic project together.

**Comment by Benjy1979** [comment]
Turned out in my environment file I had at some point (much to my own irritation)  in the past set a ENV value to a function like:
ENV.addPlannerRoutes = function(router) {};
  
It seems to halt the ember serve in random places so it's obviously not a ember-css-transitions. I think I was unlucky that it was sticking a bit on ember-css-transitions yesterday.
Thanks for adding node to the tests anyway.
