### ISSUE TITLE
Animate out child elements

### ISSUE THREAD

**Issue by jeffsawatzky** [peec/ember-css-transitions#48]
I have a situation where I show/hide a parent element based on a boolean, and then I animate some child elements in/out.

When the parent element is shown, the child elements properly animate in. However, when the parent element is removed, the child elements don't have time to animate out.

I previously worked around this by using properties as a trigger to start the child animations, and then using the didTransitionOut to determine when to remove the parent element, but it seems like the newer version has removed the ability to control the animations via a property.

**Comment by miguelcobain** [comment]
What do you mean by "the ability to control the animations via a property"?
Perhaps you could show some code that was possible in previous version that isn't now.

**Comment by jeffsawatzky** [comment]
Have a look at the previous document:
http://peec.github.io/ember-css-transitions/versions/v1.1.0/docs/add-removal
Note how the animation is triggered by the `isImportant` property/argument.

I see that was removed in favour of just using classes:
http://peec.github.io/ember-css-transitions/docs/add-removal

I worked around this for now by first removing the child elements, and then when the child element's animations are complete I remove the parent element using the didTransitionOut action.

Am I going about this in a way that is harder than it should be? Do you have any examples of how to add/remove a parent element and allow child elements to animation in/out?

**Comment by miguelcobain** [comment]
@jeffsawatzky can you please provide a very concrete example?
On that old documentation page I don't see how we're animating child elements in/out.

**Comment by jeffsawatzky** [comment]
@miguelcobain the example I showed isn't an example of animating child elements. It was an example of using a property/argument as a trigger for the animation instead of relying on the insertion/removal of the element.

I used this feature to make child animations work properly, and now with this feature gone I need to come up with some other technique to render child elements. If there is a better way to animate child elements when removing a parent element I would love to know it. Otherwise, is it possible to get this feature back? Thanks!

**Comment by pdud** [comment]
@jeffsawatzky, here is one way to render child parent with the current setup. `showParent` could be from the calling context too.

What do you think?

I'd be curious of a snippet like below on how you did it before using the property as the trigger too.

```component.js
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';

export default class ParentComponent extends Component {
  @tracked
  showParent = true;

  @tracked
  showChild = true;

  @action
  childTransitionedOut() {
    this.showParent = false;
  }

  @action
  transitionOutChild() {
    this.showChild = false;
  }
}

```
```component.hbs
{{#if this.showParent}}
  <div class="p-4 bg-blue" {{css-transition leaveClass="opacity-100" leaveActiveClass="duration-1000 ease-in transition-all" leaveToClass="opacity-0"}}>
    Hello

    {{#if this.showChild}}
      <div class="overflow-hidden bg-red" {{css-transition enterClass="opacity-0" enterActiveClass="duration-1000 ease-in transition-all" enterToClass="opacity-100" leaveClass="opacity-100 h-48" leaveActiveClass="duration-1000 ease-out transition-all" leaveToClass="opacity-0 h-0" didTransitionOut=this.childTransitionedOut}}>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

        <button class="button" type="button" {{on "click" this.transitionOutChild}}>Hide me</button>
      </div>
    {{/if}}
  </div>
{{/if}}
```

**Comment by jeffsawatzky** [comment]
Yeah, I managed to work around this by doing something similar.
