### ISSUE TITLE
What's the correct pattern for use with Tailwind?

### ISSUE THREAD

**Issue by roomman** [peec/ember-css-transitions#51]
Hi, I've had a few challenges getting the Addon working with Tailwind classes. I've cracked it now but I just wanted to check-in to see if there's a pattern that could be teased out in the documentation.

I recently added a slide over component to a project, using code taken directly from TailwindUI. In the code's documentation these were the instructions for adding a transition:
```
<!--
  Slide-over panel, show/hide based on slide-over state.

  Entering: "transform transition ease-in-out duration-500 sm:duration-700"
    From: "translate-x-full"
    To: "translate-x-0"
  Leaving: "transform transition ease-in-out duration-500 sm:duration-700"
    From: "translate-x-0"
    To: "translate-x-full"
-->
```
Accordingly, for my component, I used the Addon in this way:
```
  {{css-transition
    enterClass="transform transition ease-in-out duration-500 sm:duration-700"
    enterActiveClass="translate-x-full"
    enterToClass="translate-x-0"
    leaveClass="transform transition ease-in-out duration-500 sm:duration-700"
    leaveActiveClass="translate-x-0"
    leaveToClass="translate-x-full"
    didTransitionOut=@didTransitionOut
    didTransitionIn=@didTransitionIn
  }}
```
It didn't work. The component just appeared and vanished with no translation at all. After a bit of playing around, I got it working with the following:
```
  {{css-transition
    enterClass="translate-x-full"
    enterActiveClass="transform transition ease-in-out duration-500 sm:duration-700"
    enterToClass="translate-x-0"
    leaveClass="translate-x-0"
    leaveActiveClass="transform transition ease-in-out duration-500 sm:duration-700"
    leaveToClass="translate-x-full"
    didTransitionOut=@didTransitionOut
    didTransitionIn=@didTransitionIn
  }}
```
Based on this, and in terms of a pattern other can follow, am I right in thinking that Tailwind's documents map to the Addon's API like so?:

Entering => enterActiveClass
From => enterClass
To => enterToClass
Leaving => leaveActiveClass
From =>  leaveClass
To => leaveToClass

Many thanks for your time and help 😁

**Comment by miguelcobain** [comment]
@roomman your summary is correct.
We copied the class name arguments from vue: https://vuejs.org/v2/guide/transitions.html#Transition-Classes

Using Vue and ember-css-transitions should be pretty similar: https://twitter.com/adamwathan/status/1118670393030537217?s=20

Please feel free to PR/suggest improvements we could make to the documentation.

**Comment by roomman** [comment]
Cheers for confirming @miguelcobain, I'll sort a PR 👍🏻
