### ISSUE TITLE
Leave* transitions only work on the root element

### ISSUE THREAD

**Issue by btecu** [peec/ember-css-transitions#61]
When it comes to the _exit_ transitions, this works:
```hbs
<div {{css-transition ...}}>
  // Content
</div>
```

However, this does not work:
```hbs
<div class="something">
  <div {{css-transition ...}}>
    // Content
  </div>
</div>
```

**Comment by miguelcobain** [comment]
Is this something you could provide a failing test for?

**Comment by btecu** [comment]
@miguelcobain see #62.

**Comment by miguelcobain** [comment]
I see what is happening. In the template:

```hbs
{{#if this.show}}
  <div class="random-class">
    <div
      id="my-element"
      {{css-transition
        leaveClass="opacity-100"
        leaveActiveClass="duration-1000"
        leaveToClass="opacity-0"
      }}
    >
      <p class="content">Çup?</p>
    </div>
  </div>
{{/if}}
```

When `this.show` is set to `false`, the `<div class="random-class">` is immediately removed from DOM. The modifier tries to add a clone to the DOM for the leave transition to take place and it tries to add it to the modifier element's **parent**. However, that parent is detached from DOM already (as it should be).

Ideally, the modifier would add a clone of the whole template inside the `{{#if`, however, there's no way for us to know what **is** inside the if.

Perhaps we could support these kinds of situations with a new argument like `parentSelector=".random-class"`. This way we would know what element we should clone. It's a complicated scenario and I'm not sure if that argument name illustrates what is actually going on.

Any thoughts?

**Comment by btecu** [comment]
That would work. Another option would be something like `nestLevel={{1}}`, in which case it would use `this.element.parentElement` for cloning:
```js
let element = this.element;
for (let i = this.args.nestLevel ?? 0; i > 0; i--) {
  element = element.parentElement;
}
```

**Comment by miguelcobain** [comment]
That's also an interesting idea.

It just occurred to me that Ember now has contextual modifiers. So, in principle, an api like the following would be possible:

```hbs
<TransitionContainer as |css-transition|>
  {{#if this.show}}
    <div class="random-class">
      <div
        {{css-transition
          leaveClass="opacity-100"
          leaveActiveClass="duration-1000"
          leaveToClass="opacity-0"
        }}
      >
        <p class="content">Çup?</p>
      </div>
    </div>
  {{/if}}
</TransitionContainer>
```

Or maybe the top component should incorporate the conditional itself with

```hbs
{{#transition-if this.show as |css-transition|}}
  <div class="random-class">
    <div
      {{css-transition
        leaveClass="opacity-100"
        leaveActiveClass="duration-1000"
        leaveToClass="opacity-0"
      }}
    >
      <p class="content">Çup?</p>
    </div>
  </div>
{{/transition-if}}
```

Used curly syntax to make it closer to `{{#if` and also matches ember-animated api.

I think there are ways to make this new component a tagless one, so it would effectively act as a "marker" on the template, without affecting the DOM. This way, we know what to clone and where to attach the clone.

On a second thought, there are times when the animation isn't triggered by an if at all, but via a component/route rendering/teardown. So, the parent component would have to be generic enough to accommodate both cases.

Maybe something like this for "conditional" cases:

```hbs
{{#transition this.show as |css-transition|}}
  <div class="random-class">
    <div
      {{css-transition
        leaveClass="opacity-100"
        leaveActiveClass="duration-1000"
        leaveToClass="opacity-0"
      }}
    >
      <p class="content">Çup?</p>
    </div>
  </div>
{{/transition}}
```

and omitting the value would just run the transitions on component/route rendering/teardown:

```hbs
{{#transition as |css-transition|}}
  <div class="random-class">
    <div
      {{css-transition
        leaveClass="opacity-100"
        leaveActiveClass="duration-1000"
        leaveToClass="opacity-0"
      }}
    >
      <p class="content">Çup?</p>
    </div>
  </div>
{{/transition}}
```


I need to think a bit. 🤔 
Any thoughts are welcome.

**Comment by btecu** [comment]
@miguelcobain Since this is likely an edge case, I would probably take the simpler path, with an argument, either the selector of the parent like you mentioned or some type of `nestLevel` specifier.

**Comment by robclancy** [comment]
For me I think it would be cool to "tag" a parent as the required clone using another modifier.

```html
<div class="random-class" {{css-transition-parent}}>
  <div
      {{css-transition
        leaveClass="opacity-100"
        leaveActiveClass="duration-1000"
        leaveToClass="opacity-0"
      }}
    >
      <p class="content">Çup?</p>
    </div>
</div>
```

Where is just adds an attribute that the inner one selects by, similar to how `group` works in tailwindcss. 

Although I also agree it should probably just be a selector.

**Comment by evoactivity** [comment]
I need to implement a tailwind ui sidebar which has several children use css transitions on enter/exit. The parent div has no transitions. I quite like @robclancy's suggestion as an api, but I'm not sure how that would be implemented.

Is there anything we can do to help move this issue along? If @miguelcobain could give a breif overview of what would need changing I could maybe pick it up and take a stab at a draft PR. I think being able to choose the parent element that gets cloned would allow multiple children to use a css-transition all within a single if statement wrapping the entire block.

**Comment by miguelcobain** [comment]
Please test version `3.1.0` that was just released. I implemented this as a `parentSelector` argument.
Please let me know if it is working correctly!
